version: '3.8'

services:
  edgemind-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edgemind-web
    ports:
      - "8501:8501"  # Streamlit UI
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - ENVIRONMENT=docker
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./web:/app/web
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - edgemind-network
    command: streamlit run web/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  edgemind-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edgemind-api
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"  # FastAPI
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - ENVIRONMENT=docker
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - edgemind-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: edgemind-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - edgemind-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  edgemind-network:
    driver: bridge

volumes:
  redis-data: