# docker-compose-research.yml
version: '3.8'

services:
  research-vm:
    image: ubuntu:22.04
    container_name: research-sandbox
    command: sleep infinity
    mem_limit: 2g
    cpus: 2
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - research-data:/workspace:rw
    networks:
      - research-network
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: "no"

  agent-controller:
    build: .
    ports:
      - "8502:8501"  # Agent control interface
    depends_on:
      - research-vm
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - research-network
    environment:
      - STREAMLIT_SERVER_PORT=8501

volumes:
  research-data:
    driver: local

networks:
  research-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16